[package]
name = "league_overlay"
version = "0.1.0"
edition = "2024"

[profile.release]
strip = true

[features]
default = ["res_2560"]
res_1920 = []
res_2560 = []

[dependencies]
tokio = { version = "1.0", features = ["full"] }
reqwest = { version = "0.11", features = ["json", "rustls-tls"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
anyhow = "1.0"
riven = "2.69.0"
egui = "0.31.1"
eframe = "0.31.1"

[package.metadata.windows]
subsystem = "windows"